services:
  - type: web
    name: acencia-unified-app
    env: python
    plan: free
    buildCommand: |
      pip install -r backend/requirements.txt
      (cd frontend && yarn install && yarn build)
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    cwd: backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name-here
          property: internalUrl